// Lista de profissionais (simulados)
const professionals = [
  {
    id: 1,
    name: "Marcus Johnson",
    role: "Consultor de Trabalho Remoto",
    location: "Austin, TX",
    image: "src/Perfil-Foto1.jpg",
    company: "WorkAnywhere Co.",
    email: "marcus.j@workanywhere.com",
    phone: "+1 (555) 234-5678",
    website: "https://workanywhere.com",
    about: "Ajudando organizações a fazer a transição para modelos de trabalho remoto e híbrido eficazes. Especialista em colaboração digital e gestão de equipes distribuídas.",
    skills: ["Estratégia de Trabalho Remoto", "Gestão de Equipes", "Ferramentas Digitais", "Gestão de Mudanças","Comunicação"],
    traits: ["Estratégico", "Focado em Pessoas", "Organizado", "Visionário"],
    workStyle: ["Orientado a Resultados", "Híbrido", "Colaborativo", "Proativo"],
    interests: ["Nomadismo Digital", "Produtividade", "Equilíbrio Trabalho-Vida", "Viagens"],
    academic: ["MBA em Gestão de Pessoas - Harvard Business School", "Bacharelado em Psicologia Organizacional" ],
    experience: ["8 anos como consultor de trabalho remoto","Projetos em empresas globais distribuídas"],
    hobbies: ["Liderança colaborativa","Empatia com equipes multiculturais","Trilhas e fotografia de paisagens"]
  },
  {
    id: 2,
    name: "Sarah Chen",
    role: "Especialista em Ética de IA",
    location: "São Francisco, CA",
    image: "src/Perfil-Foto2.jpg",
    company: "FutureTech Labs",
    email: "sarah.chen@futuretechlabs.com",
    phone: "+1 (555) 301-8890",
    website: "https://futuretechlabs.com",
    about: "Apaixonada por garantir que o desenvolvimento de IA esteja alinhado com valores humanos e bem social. Liderando iniciativas em implementação responsável de IA.",
    skills: ["Ética em IA", "Aprendizado de Máquina", "Desenvolvimento de Políticas", "Pesquisa", "Python"],
    traits: ["Analítica", "Colaborativa", "Atenta a detalhes"],
    workStyle: ["Baseada em Evidências", "Colaborativo", "Documentado"],
    interests: ["IA Responsável", "Regulação", "Bias Mitigation"],
    academic: ["Mestrado em Ciência da Computação","Especialização em Ética em Inteligência Artificial" ],
    experience: ["Liderança em projetos de IA responsável","Palestrante sobre IA responsável"],
    hobbies: ["Pensamento crítico","Trabalho em equipe","Hackathons, arte generativa, comunidades tech"]
  },
  {
    id: 3,
    name: "Priya Patel",
    role: "Diretora de Sustentabilidade",
    location: "Seattle, WA",
    image: "src/Perfil-Foto3.jpg",
    company: "GreenFuture Corp",
    email: "priya.patel@greenfuturecorp.com",
    phone: "+1 (555) 734-2201",
    website: "https://greenfuturecorp.com",
    about: "Impulsionando iniciativas corporativas de sustentabilidade e responsabilidade ambiental. Comprometida em criar um futuro mais verde através da inovação empresarial.",
    skills: ["ESG", "Relatórios de Sustentabilidade", "Análise de Ciclo de Vida", "Neutralidade de Carbono"],
    traits: ["Orientada a Impacto", "Comunicativa", "Liderança"],
    workStyle: ["Interfuncional", "Metódica", "Orientada a Metas"],
    interests: ["Energia Limpa", "Economia Circular", "Educação Ambiental"],
    academic: [
      "MBA em Sustentabilidade",
      "Bacharelado em Administração"
    ],
    experience: [
      "10 anos liderando projetos ESG",
      "Implementação de políticas ambientais corporativas"
    ],
    hobbies: ["Sustentabilidade", "Voluntariado ambiental", "Trilhas"]
  },
  {
    id: 4,
    name: "David Kim",
    role: "Líder de Design UX",
    location: "Nova York, NY",
    image: "src/Perfil-Foto4.jpg",
    company: "DesignFirst Studio",
    email: "david.kim@designfirst.studio",
    phone: "+1 (555) 642-1144",
    website: "https://designfirst.studio",
    about: "Criando experiências digitais intuitivas e acessíveis. Defensor do design centrado no ser humano na era da automação.",
    skills: ["Pesquisa com Usuários", "Acessibilidade", "Arquitetura da Informação", "Design de Interação"],
    traits: ["Empático", "Curioso", "Sistêmico"],
    workStyle: ["Colaborativo", "Prototipação Rápida", "Iterativo"],
    interests: ["A11y", "Tipografia", "Design Systems"],
    academic: ["Mestrado em Design de Interação"],
    experience: ["Liderança de times de UX", "Pesquisa com usuários"],
    hobbies: ["Acessibilidade", "Tipografia", "Museus"]
  },
  {
    id: 5,
    name: "Elena Rodriguez",
    role: "Desenvolvedora Blockchain",
    location: "Miami, FL",
    image: "src/Perfil-Foto5.jpg",
    company: "CryptoInnovate",
    email: "elena.rodriguez@cryptoinnovate.io",
    phone: "+1 (555) 775-0098",
    website: "https://cryptoinnovate.io",
    about: "Construindo o futuro descentralizado. Especializada em contratos inteligentes e infraestrutura blockchain para aplicações de próxima geração.",
    skills: ["Smart Contracts", "Solidity", "EVM", "Segurança Web3"],
    traits: ["Detalhista", "Resiliente", "Exploratória"],
    workStyle: ["Remote-First", "Test-Driven", "Open Source"],
    interests: ["DeFi", "NFTs", "Criptografia"],
    academic: ["Bacharelado em Ciência da Computação"],
    experience: ["Smart contracts", "Infraestrutura Web3"],
    hobbies: ["Cripto", "Hackathons", "Surf"]
  },
  {
    id: 6,
    name: "James Mitchell",
    role: "Gerente de Aprendizagem e Desenvolvimento",
    location: "Boston, MA",
    image: "src/Perfil-Foto6.jpg",
    company: "SkillBridge Academy",
    email: "james@skillbridge.academy",
    phone: "+1 (555) 210-4433",
    website: "https://skillbridge.academy",
    about: "Capacitando profissionais a prosperar no futuro do trabalho através de programas contínuos de aprendizagem e desenvolvimento de habilidades.",
    skills: ["L&D", "Design Instrucional", "Academias Corporativas", "Medição de Impacto"],
    traits: ["Comunicador", "Mentor", "Organizado"],
    workStyle: ["Facilitador", "Baseado em Dados", "Colaborativo"],
    interests: ["Aprendizagem Contínua", "Coaching", "Comunidades"],
    academic: ["Psicologia Organizacional"],
    experience: ["Programas L&D", "Academias corporativas"],
    hobbies: ["Leitura", "Mentoria", "Ciclismo"]
  },
  {
    id: 7,
    name: "Ana Silva",
    role: "Cientista de Dados",
    location: "São Paulo, SP",
    image: "src/Perfil-Foto7.jpg",
    company: "DataInsights Pro",
    email: "ana.silva@datainsights.pro",
    phone: "+55 11 98765-4321",
    website: "https://datainsights.pro",
    about: "Transformando dados complexos em insights acionáveis. Especialista em análise preditiva e visualização de dados para tomada de decisões estratégicas.",
    skills: ["Modelagem Preditiva", "ML Ops", "Visualização", "SQL/Python"],
    traits: ["Curiosa", "Lógica", "Comunicativa"],
    workStyle: ["Hipótese-Driven", "Iterativo", "Colaborativo"],
    interests: ["Comunidades de Dados", "Café", "Open Data"],
    academic: ["Mestrado em Estatística"],
    experience: ["Modelagem preditiva", "Dashboards executivos"],
    hobbies: ["Corrida", "Café", "Comunidades de dados"]
  },
  {
    id: 8,
    name: "Thomas Anderson",
    role: "Especialista em Segurança Cibernética",
    location: "Londres, Reino Unido",
    image: "src/Perfil-Foto8.jpg",
    company: "SecureShield Systems",
    email: "thomas.anderson@secureshield.systems",
    phone: "+44 20 7946 1110",
    website: "https://secureshield.systems",
    about: "Protegendo empresas contra ameaças cibernéticas avançadas. Especializado em arquitetura de segurança zero-trust e resposta a incidentes.",
    skills: ["Zero-Trust", "Blue Team", "Threat Modeling", "Resposta a Incidentes"],
    traits: ["Analítico", "Discreto", "Preventivo"],
    workStyle: ["Procedural", "Documentado", "On-Call"],
    interests: ["CTFs", "Criptografia", "Caminhadas"],
    academic: ["Certificações CISSP/CEH"],
    experience: ["Blue team", "Resposta a incidentes"],
    hobbies: ["CTFs", "Criptografia", "Caminhadas"]
  },
  {
    id: 9,
    name: "Sophia Martinez",
    role: "Gerente de Produto Digital",
    location: "Barcelona, Espanha",
    image: "src/Perfil-Foto9.jpg",
    company: "InnovateTech",
    email: "sophia@innovatech.com",
    phone: "+34 91 123 4567",
    website: "https://innovatech.com",
    about: "Liderando o desenvolvimento de produtos digitais inovadores do conceito ao lançamento. Focada em criar experiências que os usuários adoram.",
    skills: ["Roadmaps", "Descoberta", "Métricas de Produto", "Go-To-Market"],
    traits: ["Empática", "Orientada a Valor", "Comunicadora"],
    workStyle: ["Cross-Functional", "Data-Informed", "Iterativo"],
    interests: ["Startups", "Fotografia", "Viagens"],
    academic: ["MBA em Produto"],
    experience: ["Roadmaps", "Descoberta de produto"],
    hobbies: ["Fotografia", "Viagens", "Startups"]
  },
  {
    id: 10,
    name: "Raj Sharma",
    role: "Estrategista de Marketing Digital",
    location: "Mumbai, Índia",
    image: "src/Perfil-Foto10.jpg",
    company: "GrowthLab Agency",
    email: "raj@growthlab.agency",
    phone: "+91 22 4001 7788",
    website: "https://growthlab.agency",
    about: "Criando estratégias de marketing digital orientadas por dados que impulsionam crescimento. Especialista em SEO, marketing de conteúdo e análise de performance.",
    skills: ["SEO/SEM", "Conteúdo", "Automação de Marketing", "Analytics"],
    traits: ["Criativo", "Analítico", "Orientado a Crescimento"],
    workStyle: ["Testar e Aprender", "Data-Driven", "Colaborativo"],
    interests: ["Blogs", "Culinária", "Críquete"],
    academic: ["Marketing"],
    experience: ["SEO/SEM", "Conteúdo e Analytics"],
    hobbies: ["Críquete", "Blogs", "Culinária"]
  },
  {
    id: 11,
    name: "Lisa Wang",
    role: "Especialista em RH Tech",
    location: "Singapura",
    image: "src/Perfil-Foto11.jpg",
    company: "TalentFlow Solutions",
    email: "lisa@talentflow.solutions",
    phone: "+65 6123 7788",
    website: "https://talentflow.solutions",
    about: "Revolucionando o recrutamento e gestão de talentos através de tecnologia. Implementando soluções de RH baseadas em IA para melhorar a experiência do colaborador.",
    skills: ["ATS", "People Analytics", "Employer Branding", "Onboarding"],
    traits: ["Relacionadora", "Organizada", "Orientada a Pessoas"],
    workStyle: ["Parceria com Negócio", "Dados + Intuição", "Colaborativo"],
    interests: ["Yoga", "Leitura", "Eventos de Tech-RH"],
    academic: ["Administração / RH"],
    experience: ["ATS", "People Analytics"],
    hobbies: ["Yoga", "Leitura", "Eventos de tech-RH"]
  },
  {
    id: 12,
    name: "Carlos Mendes",
    role: "Gerente de Mídias Sociais",
    location: "Lisboa, Portugal",
    image: "src/Perfil-Foto12.jpg",
    company: "Social Buzz Agency",
    email: "carlos@socialbuzz.agency",
    phone: "+351 21 555 9090",
    website: "https://socialbuzz.agency",
    about: "Criando estratégias de mídias sociais envolventes que constroem comunidades e impulsionam engajamento. Especialista em marketing de influenciadores e conteúdo viral.",
    skills: ["Conteúdo Viral", "Influenciadores", "Social Analytics", "Paid Social"],
    traits: ["Criativo", "Ágil", "Comunicativo"],
    workStyle: ["Always-On", "Colaborativo", "Orientado a Comunidade"],
    interests: ["Tendências", "Música", "Fotografia"],
    academic: ["Comunicação Social"],
    experience: ["Social media", "Growth em redes"],
    hobbies: ["Fotografia", "Tendências", "Música"]
  }
];